module.exports = [
  'evento',
  'eventos',
  'estudiante',
  'estudiantes',
  'caminar',
  'Revelación',
  'VISUALIZACIÓN VISUAL',
  'VISITE VISUAL',
  'PANTALLA VISUAL',
  'esquema ',
  'contorno',
  'relación',
  'relación con Dios',
  'relación personal',
  'en lo que se refiere',
  'Cerrar en la oración',
  'chart',
  'guía',
  'Discusión en grupo',
  'Discusión grupal',
  'el trabaja',
  'de veras',
  'probablemente',
  'reta',
  'pretenden',
  'pretender',
  'fundacional',
  'seria',
  'severa',
  'imagen',
  'influenciar',
  'Jude',
  'el trabajo',
  'los motivos',
  'los estándares',
  'la gente',
  'comando',
  'Comandos',
  'tiempos',
  'tiempos de',
  'estimula',
  'Desafíe ',
  'nuestras mentes',
  'nuestras vidas',
  'trabajar',
  'trabaje',
  'nótese',
  'note que',
  'Paul',
  'orar por',
  'Peter',
  'colocando',
  'honra de Dios',
  'Distribuya la Hoja de Trabajo',
  'repasar',
  'review',
  'Revise',
  'revisar',
  'James',
  'de acuerdo con',
  'violación de',
  'violaciones',
  'un individuo',
  'verso',
  'versos'
]
